" use vim-plug as plugin manager. Automatically executes filetype plugin indent on and syntax enable.
set nocompatible              " be iMproved, required

" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins

" Install NERDtree
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'

" Install rust.vim
Plug 'rust-lang/rust.vim'

" Install vim-go
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" Install lightline.vim
Plug 'itchyny/lightline.vim'

" Install Nord color scheme
Plug 'arcticicestudio/nord-vim'

" Install solarized color scheme
Plug 'altercation/vim-colors-solarized'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()


" use nord color scheme as default
syntax on
colorscheme nord
