export PATH=/usr/local/bin:/usr/bin/sbin:$PATH

# Golang
export GOROOT=/usr/local/opt/go/libexec
export DEFAULT_GOPATH=$HOME/workshop/go
export GOPATH=$DEFAULT_GOPATH:$HOME/workshop/github/golang/go
export GOBIN=$DEFAULT_GOPATH/bin

# export GOPROXY=https://goproxy.io
export GOPROXY=https://athens.azurefd.net

alias gws="cd $DEFAULT_GOPATH/src"
alias ggh="cd $DEFAULT_GOPATH/src/github.com"
alias gsc="cd $HOME/workshop/github/golang/go"

export PATH=$PATH:$GOROOT/bin:$DEFAULT_GOPATH/bin

# Java
export JAVA_HOME=$(/usr/libexec/java_home)
export GRADLE_HOME=/usr/local/opt/gradle/libexec
export MAVEN_OPTS="-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"

export PATH=$PATH:$GRADLE_HOME/bin

# Python
alias ipy="python -c 'import IPython; IPython.terminal.ipapp.launch_new_instance()'"

# Github
eval "$(hub alias -s)"
alias git='LANG=en_US git'

# Ruby
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Firefox
export FIREFOX_HOME=/Applications/Firefox.app/Contents/MacOS
export PATH=$PATH:$FIREFOX_HOME

# Flutter
export FLUTTER_HOME=$HOME/workshop/flutter
export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

export PATH=$PATH:$FLUTTER_HOME/bin

# autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Kubernetes
# load kubectl aliases
[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases

# print kubectl full command before running
function kubectl() { echo "+ kubectl $@"; command kubectl $@; }

# list all ready nodes
alias kgnoa='kubectl get node | grep -v "NotReady"'
alias kgnoasl='kubectl get node --show-labels | grep -v "NotReady"'

# Rust
export PATH=$HOME/.cargo/bin:$PATH
alias sgh="cd $HOME/workshop/github/shohi"

# Nim
export PATH=$HOME/.nimble/bin:$PATH
export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles
